### ISSUE TITLE
talosctl vedorhash

### ISSUE THREAD

**Issue by soulwhisper** [bjw-s-labs/nix-config#69]
# Details

**What steps did you take and what happened:**

Hello, I am following your project. As I noticed, everytime talosctl updates, we have to fix its vendorhash.
During my reseach, I found this [project](https://github.com/nix-community/gomod2nix), and this [post](https://www.tweag.io/blog/2021-03-04-gomod2nix/).
Since I am not famliar with Golang, could you update the code to include this vendorhash fix?

**What did you expect to happen:**
Manually update talosctl vendorhash no more.

**Comment by bjw-s** [comment]
Hi, thanks for raising the suggestion! This is definitely something that is a bit annoying, but at the same time I think it may also be by design to force package authors to make sure no "bad" dependencies get built? 

I will see if there is an elegant solution. The biggest issue is that I don't own any of the upstream code. That means I need to check out the upstream repo at the correct tag, run whichever tools required to populate the hash and then feed that back into the nixpkg. All of this would make the build pipe quite complex I think.

**Comment by soulwhisper** [comment]
Agreed. I tested some methods about set vendorHash to other values, but they all failed the build. However I get this snipplet of code about calculating hash. [source](https://github.com/MinaProtocol/mina/blob/develop/nix/go.nix). So there might be a method to extract `go.sum` and `go.mod` from certain release then got updated value. Just a tip.
```go
    vendorHash = let
      hashes = final.lib.importJSON ./libp2p_helper.json;
      # sanity check, to make sure the fixed output drv doesn't keep working
      # when the inputs change
    in if builtins.hashFile "sha256" ../src/app/libp2p_helper/src/go.mod
    == hashes."go.mod"
    && builtins.hashFile "sha256" ../src/app/libp2p_helper/src/go.sum
    == hashes."go.sum" then
      hashes.vendorSha256
    else
      final.lib.warn ''
        Below, you will find an error about a hash mismatch.
        This is likely because you have updated go.mod and/or go.sum in libp2p_helper.
        Please, locate the "got: " hash in the aforementioned error. If it's in SRI format ([35;1msha256-<...>[31;1m), copy the entire hash, including the `[35;1msha256-[31;1m'. Otherwise (if it's in the base32 format, like `[35;1msha256:<...>[31;1m'), copy only the base32 part, without `[35;1msha256:[31;1m'.
        Then, run [37;1m./nix/update-libp2p-hashes.sh [35;1m"<got hash here>"[31;0m
      '' final.lib.fakeHash;
```

**Comment by soulwhisper** [comment]
I found a more reasonable solution [here](https://github.com/wozeparrot/seaweedfs-nix/blob/main/update.sh) and related [action](https://github.com/wozeparrot/seaweedfs-nix/actions/runs/11848032103/workflow), I will test if this one fits.

**Comment by bjw-s** [comment]
Thanks for this idea @soulwhisper! I've hacked around a bit and implemented a similar solution in my nvfetcher GH workflow. ❤️

**Comment by soulwhisper** [comment]
@bjw-s I think you should add a `git commit` after vendorhash updated, otherwise the changes won`t be pushed. Also, if possible, I would prefer to add changes into `peter-evans/create-pull-request`.
